# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-oidc-credential-helper" do
  name "proxmox-oidc-credential-helper"
  desc "proxmox-oidc-credential-helper utility allows to obtain credentials from Proxmox's UI using OIDC and exports them to the shell as env variables."
  homepage "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxmox-oidc-credential-helper"

  on_macos do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "4e18d54bc220de1182c6ff5e86120a7b68274851b899c932e56a8bf8dae83d96"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "632372f005e5d2ff7f818eeebbc98eabb07c59be65e284417142271f38a44771"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "d3f285252c2ba07d67c714a4d608f75a37a3b4c4b955bb9187e997d49795af51"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "2c9105c184992f97dbfbddfb4ba9e8174b471a78ef37fab44dca854dadb87a12"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-oidc-credential-helper"]
    end
  end

  # No zap stanza required
end
