# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-oidc-credential-helper" do
  name "proxmox-oidc-credential-helper"
  desc "proxmox-oidc-credential-helper utility allows to obtain credentials from Proxmox's UI using OIDC and exports them to the shell as env variables."
  homepage "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper"
  version "0.4.1-rc6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxmox-oidc-credential-helper"

  on_macos do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "053e4de96e583eb6012f27bdf6dbfaabc26742c3e2d002847511eb3987b7e57d"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "1614e170fb84f024eeedeb47f388344afb3e11d25eff918ab1b15316bca54bbc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "6adcdd4e977e5c32bfbdd0cc3c7f92c61de2fa02de07c925bd1786d8b42c6f6e"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/"
      sha256 "8a1a732a625361562d3bcb36af1baebebc00729b4429ad64251430ec553a3db1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-oidc-credential-helper"]
    end
  end

  # No zap stanza required
end
