# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-oidc-credential-helper" do
  name "proxmox-oidc-credential-helper"
  desc "proxmox-oidc-credential-helper utility allows to obtain credentials from Proxmox's UI using OIDC and exports them to the shell as env variables."
  homepage "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper"
  version "0.4.1-rc5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxmox-oidc-credential-helper"

  on_macos do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/",
        using: :homebrew_curl
      sha256 "5a767f3c8aa0775dd03a9b1604ca0b65d46523dca03280a349946f185b3d2f61"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Darwin_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/",
        using: :homebrew_curl
      sha256 "3b45105d3c49997459fdd26e9cf3195a98481cfa9c9a028280670a4fd9dd42f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_amd64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/",
        using: :homebrew_curl
      sha256 "a6769fec20784a96267ee90ccbb0ff0e113e2b09eb54e7ef1310ee4bca63eb9e"
    end
    on_arm do
      url "https://github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/releases/download/v#{version}/proxmox-oidc-credential-helper_Linux_arm64.tar.gz",
        verified: "github.com/proxmox-oidc-credential-helper/proxmox-oidc-credential-helper/",
        using: :homebrew_curl
      sha256 "01e0a36971a264874295fd2e6740615a7132f489befbdef7072b24adaa726cc5"
    end
  end

  # No zap stanza required
end
